print("open cupboard")
print("remove bag of bread from cupboard")
print("turn around to face island counter")
print("place bag of bread on island counter")
print("turn around to face cupboard")
print("remove jar of peanut butter from cupboard")
print("turn around to face island counter")
print("place jar of peanut butter on island counter")
print("turn around to face cupboard")
print("close cupboard")
print("turn around to face fridge")
print("approach refrigerator")
print("walk to fridge")
print("open refrigerator doors")
print("remove jelly from fridge")
print("close fridge doors")
print("turn around to face island counter")
print("place jelly on island counter")
print("turn towards dishware cabinet")
print("approach dishware cabinet")
print("open dishware cabinet")
print("remove plate from stack of plates")
print("close dishware cabinet")
print("turn around to face silverware drawer")
print("remove a butter knife from silverware drawer")
print("close silverware drawer")
print("turn around to face island counter")
print("place plate on island counter")
print("pick up bag of bread")
print("remove twist tie from bag of bread")
print("place bag of bread on island counter")
print("open peanut butter jar")
print("grab knife off of island counter")
print("scoop peanut butter with knife")
print("put peanut butter jar down on island counter", end='', flush=True)
print("pick up slice of bread A")
print("spread peanut butter on slice of bread A")
print("place slice of bread A on plate")
print("open jelly jar")
print("scoop jelly with knife")
print("pick up slide of bread B")
print("spread jelly on slice of bread B")
print("put butter knife down on plate")
print("pick up slice of bread A")
print("put slices of bread together, peanut butter facing meeting jelly")
print("place combined slices of bread, peanut butter, and jelly on plate (now referred to as sandwich)")
print("pick up butter knife")
print("hold sandwich down on plate")
print("cut sandwich in half")
print("turn around to face sink")
print("approach sink")
print("turn on sink")
print("rinse off butter knife")
print("place butter knife in sink")
print("turn around to face island counter")
print("approach island counter")
print("pick up open jar of peanut butter")
print("pick up peanut butter jar lid")
print("put lid back on peanut butter jar")
print("place peanut butter jar on island counter")
print("pick up open jar of jelly")
print("pick up jelly jar lid")
print("put lid back on jar of jelly")
print("pick up peanut butter jar")
print("turn around to face cupboard")
print("approach cupboard")
print("open cupboard")
print("put jar of peanut butter down in cupboard")
print("put jar of jelly down in cupboard")
print("turn around to face island counter")
print("approach island counter")
print("pick up bag of bread")
print("pick up twist tie")
print("put twist tie on bag of bread")
print("turn to face cupboard")
print("approach cupboard")
print("put the bag of bread in the cupboard")
print("close cupboard")
print("turn to face island counter")
print("approach island counter")
print("enjoy the fruits of my labor")
